# A workflow that is scheduled daily and carries out maintenance tasks.
name: Maintenance

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}

jobs:
  # A job to delete obsolete package versions (container images) from the GitHub registry.
  delete_container_images:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Delete obsolete package versions.
        uses: jenskeiner/ghcr-container-repository-cleanup-action@v1.0.0
        with:
          # Don't delete main, master, develop, semantic version tags, and pull request tags.
          exclude-tags: '^main|master|develop|\d+(?:\.\d+){0,2}|pr-\d+$'
          # Do not keep any other tags.
          keep-n-tagged: 0
          # Do not keep any other images.
          keep-n-untagged: 0
          token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true
