# A workflow that is scheduled daily and carries out maintenance tasks.
name: Maintenance

on:
  #schedule:
  #  - cron: '0 0 * * *'
  workflow_dispatch: {}

jobs:
  # A job to delete obsolete package versions (container images) from the GitHub registry.
  delete_container_images:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Delete old package versions.
        uses: jenskeiner/ghcr-cleanup-action@v1
        with:
          tags: ''  # Don't delete any specific tags.
          exclude-tags: '^main|master|develop|\d+(?:\.\d+){0,2}$'  # Don't delete main, master, develop, and semantic version tags.
          keep-n-tagged: 3  # Keep a number of the most recent remaining tags.
          keep-n-untagged: 0  # Delete all untagged images.
          token: ${{ secrets.GITHUB_TOKEN }}
          dry-run: true
