# A workflow that is scheduled daily and carries out maintenance tasks.
name: PR Closed

on:
  pull_request:
    types: [ closed ]

jobs:
  # A job to delete package versions (container images) from the GitHub registry related to the PR.
  delete_container_images:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - name: Delete PR package versions.
        uses: jenskeiner/ghcr-container-repository-cleanup-action@v1.2.0
        with:
          include-tags: pr-${{github.event.pull_request.number}}
          token: ${{ secrets.GITHUB_TOKEN }}
